//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoelScottFitness.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Joel Scott Fitness - Order #{0} Confirmation")]
        public string PurchaseConfirmation {
            get {
                return ((string)(this["PurchaseConfirmation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Joel Scott Fitness - Order #{0} Complete")]
        public string PurchaseComplete {
            get {
                return ((string)(this["PurchaseComplete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Joel Scott Fitness - Confirm Account")]
        public string ConfirmAccount {
            get {
                return ((string)(this["ConfirmAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Joel Scott Fitness - Reset Password")]
        public string ResetPassword {
            get {
                return ((string)(this["ResetPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content/Images/HallOfFame")]
        public string HallOfFameDirectory {
            get {
                return ((string)(this["HallOfFameDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content/Images/Blogs")]
        public string BlogImageDirectory {
            get {
                return ((string)(this["BlogImageDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content/Images/Plans")]
        public string PlanImageDirectory {
            get {
                return ((string)(this["PlanImageDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content/Images")]
        public string ImageDirectory {
            get {
                return ((string)(this["ImageDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content/Plans")]
        public string PlanDirectory {
            get {
                return ((string)(this["PlanDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} {1} - {2} - {3} - {4}.pdf")]
        public string PlanFilenameFormat {
            get {
                return ((string)(this["PlanFilenameFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Content/Images/Default/section1.jpg")]
        public string DefaultSectionImage1 {
            get {
                return ((string)(this["DefaultSectionImage1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Content/Images/Default/section2.jpg")]
        public string DefaultSectionImage2 {
            get {
                return ((string)(this["DefaultSectionImage2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Content/Images/Default/section3.jpg")]
        public string DefaultSectionImage3 {
            get {
                return ((string)(this["DefaultSectionImage3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Content/Images/Default/banner.jpg")]
        public string DefaultSplashImage {
            get {
                return ((string)(this["DefaultSplashImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}_BEFORE_{1}")]
        public string BeforeFileNameFormat {
            get {
                return ((string)(this["BeforeFileNameFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}_AFTER_{1}")]
        public string AfterFileNameFormat {
            get {
                return ((string)(this["AfterFileNameFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultItemQuantity {
            get {
                return ((int)(this["DefaultItemQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attempted checkout with null basket session for customer \'{0}\'.")]
        public string BasketItemsNullErrorMessage {
            get {
                return ((string)(this["BasketItemsNullErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to retrieve matching basket items from database for customer \'{0}\', id\'s s" +
            "earched were \'{1}\'.")]
        public string BasketItemsAsyncNullErrorMessage {
            get {
                return ((string)(this["BasketItemsAsyncNullErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to retrieve customer details for customer with id \'{0}\';")]
        public string GetCustomerDetailsAsyncErrorMessage {
            get {
                return ((string)(this["GetCustomerDetailsAsyncErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ooops, we cannot find your customer id, please contact customer services if this " +
            "continues.")]
        public string CustomerIdNullErrorMessage {
            get {
                return ((string)(this["CustomerIdNullErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to create guest account details for customer with emaill address \'{0}\'.")]
        public string CreateGuestDetailsFailedErrorMessage {
            get {
                return ((string)(this["CreateGuestDetailsFailedErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to find existing customer details for email address \'{0}\';")]
        public string UnableToFindExistingCustomerErrorMessage {
            get {
                return ((string)(this["UnableToFindExistingCustomerErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to update existing customer details for email address \'{0}\';")]
        public string FailedToUpdateExistingCustomerDetailsErrorMessage {
            get {
                return ((string)(this["FailedToUpdateExistingCustomerDetailsErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to retrieve plans from repository.")]
        public string FailedToRetrievePlansErrorMessage {
            get {
                return ((string)(this["FailedToRetrievePlansErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to initiate paypal payment, error details \'{0}\'.")]
        public string FailedToInitiatePayPalPaymentErrorMessage {
            get {
                return ((string)(this["FailedToInitiatePayPalPaymentErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to save items pending purchase for customer \'{0}\'.")]
        public string FailedToSaveItemsForPurchase {
            get {
                return ((string)(this["FailedToSaveItemsForPurchase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The confirmPurchaseViewModel was null")]
        public string ConfirmPurchaseViewModelNullErrorMessage {
            get {
                return ((string)(this["ConfirmPurchaseViewModelNullErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/Home/CompletePayment?")]
        public string CallbackUri {
            get {
                return ((string)(this["CallbackUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Payment completion parameter \'{0}\' is null or empty, cannot complete transaction." +
            "")]
        public string PaymentCompletionParameterNullErrorMessage {
            get {
                return ((string)(this["PaymentCompletionParameterNullErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One or more payment completion parameters were null or empty")]
        public string PaymentCompletionErrorMessage {
            get {
                return ((string)(this["PaymentCompletionErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to complete paypal payment, error details \'{0}\'.")]
        public string FailedToCompletePayPalPaymentErrorMessage {
            get {
                return ((string)(this["FailedToCompletePayPalPaymentErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to update purchase status of transaction with id \'{0}\'.")]
        public string FailedToUpdatePurchaseStatusErrorMessage {
            get {
                return ((string)(this["FailedToUpdatePurchaseStatusErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to retrieve purchase \'{0}\' associated to transaction with id \'{1}\'.")]
        public string FailedToRetrievePurchaseErrorMessage {
            get {
                return ((string)(this["FailedToRetrievePurchaseErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to send order confirmation email for transaction with id \'{0}\'.")]
        public string FailedToSendOrderConfirmationEmailErrorMessage {
            get {
                return ((string)(this["FailedToSendOrderConfirmationEmailErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to create or update questionnaire for purchase with id \'{0}\'.")]
        public string FailedToCreateOrUpdateQuestionnaireErrorMessage {
            get {
                return ((string)(this["FailedToCreateOrUpdateQuestionnaireErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks, your tailored workout plan will be with you in the next 24 hours.")]
        public string QuestionnaireCompleteConfirmationMessage {
            get {
                return ((string)(this["QuestionnaireCompleteConfirmationMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} image is empty, please re-select.")]
        public string ImageUploadErrorMessage {
            get {
                return ((string)(this["ImageUploadErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please add a comment.")]
        public string MissingCommentErrorMessage {
            get {
                return ((string)(this["MissingCommentErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to upload hall of fame images associated to purchased item id \'{0}\'.")]
        public string FailedToUploadHallOfFameImagesErrorMessage {
            get {
                return ((string)(this["FailedToUploadHallOfFameImagesErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to upload hall of fame associated to purchase item id \'{0}\'.")]
        public string FailedToUploadHallOfFameErrorMessage {
            get {
                return ((string)(this["FailedToUploadHallOfFameErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to create message for Name: \'{0}\', Email Address \'{1}\', Subject \'{2}\', Mes" +
            "sage \'{3}\'.")]
        public string FailedToCreateMessageErrorMessage {
            get {
                return ((string)(this["FailedToCreateMessageErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Re: {0}")]
        public string MessageResponseSubject {
            get {
                return ((string)(this["MessageResponseSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blackmore__s@hotmail.com")]
        public string JoelScottFitnessEmaillAddress {
            get {
                return ((string)(this["JoelScottFitnessEmaillAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to send message for Name: \'{0}\', Email Address \'{1}\', Subject \'{2}\', Messa" +
            "ge \'{3}\'.")]
        public string FailedToSendMessageErrorMessage {
            get {
                return ((string)(this["FailedToSendMessageErrorMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to find user with account name \'{0}\';")]
        public string FailedToFindUserErrorMessage {
            get {
                return ((string)(this["FailedToFindUserErrorMessage"]));
            }
        }
    }
}
