// <auto-generated />
namespace JoelScottFitness.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedhalloffamefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedhalloffamefields));
        
        string IMigrationMetadata.Id
        {
            get { return "201711241733488_Added hall of fame fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
