SET IDENTITY_INSERT [dbo].[Items] ON
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (1, N'12 Week Daily Trainer', 28.99, 0, 12, 1, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (2, N'18 Week Daily Trainer', 38.99, 0, 18, 1, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (3, N'24 Week Daily Trainer', 45.99, 0, 24, 1, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (4, N'4 Week Shred', 19.99, 0, 4, 2, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (5, N'8 Week Shred', 29.99, 0, 8, 2, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (6, N'12 Week Shred', 39.99, 0, 12, 2, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (7, N'4 Week Plan', 19.99, 0, 4, 3, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (8, N'8 Week Plan', 29.99, 0, 8, 3, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (9, N'12 Week Plan', 39.99, 0, 12, 3, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (10, N'4 Week Plan', 19.99, 0, 4, 4, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (11, N'8 Week Plan', 29.99, 0, 8, 4, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (12, N'12 Week Plan', 39.99, 0, 12, 4, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (13, N'4 Week Plan', 19.99, 0, 4, 5, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (14, N'8 Week Plan', 29.99, 0, 8, 5, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (15, N'12 Week Plan', 39.99, 0, 12, 5, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (16, N'4 Week Plan', 19.99, 0, 4, 6, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (17, N'8 Week Plan', 29.99, 0, 8, 6, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (18, N'12 Week Plan', 39.99, 0, 12, 6, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (19, N'4 Week Plan', 19.99, 0, 4, 7, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (20, N'8 Week Plan', 29.99, 0, 8, 7, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (21, N'12 Week Plan', 39.99, 0, 12, 7, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (22, N'4 Week Plan', 20.99, 0, 4, 8, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (23, N'8 Week Plan', 30.99, 0, 6, 8, N'PlanOption')
INSERT INTO [dbo].[Items] ([Id], [Description], [Price], [ItemType], [Duration], [PlanId], [Discriminator]) VALUES (24, N'12 Week Plan', 27.99, 0, 12, 8, N'PlanOption')
SET IDENTITY_INSERT [dbo].[Items] OFF
