SET IDENTITY_INSERT [dbo].[Plans] ON
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (1, N'Lean Body', N'It doesn''t matter what shape you''re in, your age, or how many diet programs you''ve tried. You can transform your body and become leaner and stronger', N'Get Leaner And Stronger', 0, N'/Content/Images/Plans/male-plan1.jpg', N'/Content/Images/Plans/male-plan1.jpg', 0, N'2017-12-17 23:27:39', NULL, 0)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (2, N'Shortcut to Shred', N'Get ready to burn fat, boost confidence and get in the best shape of your life! With as little cardio as possible and an enjoyable diet, get ready for.. The Shortcut to Shred!', N'Get Shredded!', 0, N'/Content/Images/Plans/male-plan2.jpg', N'/Content/Images/Plans/six-pack-abs_14_3.jpg', 0, N'2017-12-17 23:27:39', N'2018-01-26 22:28:35', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (3, N'The Hulk Effect', N'You want it all! Solid muscle, with impressive strength to back it up. Combining compound strength training with a bodybuilding approach.. GET BIGGER, GET STRONGER!', N'Maximum Strength & Size', 0, N'/Content/Images/Plans/male-plan3.jpg', N'/Content/Images/Plans/4b0c8967bedbd245dce489047781ebbd_hd.jpg', 0, N'2017-12-17 23:27:39', N'2018-01-26 22:16:42', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (4, N'Project Mass', N'Project Mass is a next level training, nutrition, and supplement program, designed to build as much muscle as possible, in the shortest space of time.. This is how you grow!', N'Muscle Building Blueprint', 0, N'/Content/Images/Plans/male-plan4.jpg', N'/Content/Images/Plans/male-plan4.jpg', 0, N'2017-12-17 23:27:39', N'2018-01-26 16:07:57', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (5, N'Wonder Woman Physique', N'Shape up, gain strength, gain confidence.. Look wonderful!', N'Shape & Strength Shortcut', 0, N'/Content/Images/Plans/female-plan1.jpg', N'/Content/Images/Plans/female-plan1.jpg', 1, N'2017-12-17 23:27:39', N'2018-01-26 20:14:06', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (6, N'Ultimate Booty Builder', N'Specified training to get the best results in the shortest space of time.. Get ready to blow up that butt!', N'Booty Building Trainer', 0, N'/Content/Images/Plans/female-plan2.jpg', N'/Content/Images/Plans/female-fitness-motivation.jpg', 1, N'2017-12-17 23:27:39', N'2018-01-26 21:35:51', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (7, N'Beach Body', N'Holiday booked? Summer on the way? Dust off those bikinis and get the body you''ve always wanted!', N'Bikini ready, in no time!', 0, N'/Content/Images/Plans/female-plan3.jpg', N'/Content/Images/Plans/beach-body-waist-slimming-workout-spotebi.jpg', 1, N'2017-12-17 23:27:39', N'2018-01-26 21:35:28', 1)
INSERT INTO [dbo].[Plans] ([Id], [Name], [Description], [BannerHeader], [BannerColour], [ImagePathMedium], [ImagePathLarge], [TargetGender], [CreatedDate], [ModifiedDate], [Active]) VALUES (8, N'Crossfit Crazy', N'No time? No equipment? No space? No problem. This travel-friendly, CrossFit-inspired workout will blast fat and sculpt muscle in minutes. No excuses!', N'The Do-Anywhere CrossFit Workout', 0, N'/Content/Images/Plans/female-plan4.jpg', N'/Content/Images/Plans/female-plan4.jpg', 1, N'2017-12-17 23:27:39', NULL, 0)
SET IDENTITY_INSERT [dbo].[Plans] OFF
